services:
  comfyui:
    container_name: comfyui-cu124
    image: yanwk/comfyui-boot:cu124-slim
    stdin_open: true
    tty: true
    ports:
      - "8288:8188"
    volumes:
      - "/docker/ComfyUIdocker:/root"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  comfyui: {}
