version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Use all available GPUs
              count: all
              capabilities: [gpu]
    networks:
      - searxng

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "WEBUI_SECRET_KEY="
      - "RAG_WEB_SEARCH_ENGINE=searxng"
      - "SEARXNG_QUERY_URL=http://searxng:8080/search?q=<<query>>"
      - "ENABLE_RAG_WEB_SEARCH=true"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - searxng

volumes:
  ollama: {}
  open-webui: {}

networks:
  searxng:
    name: searxng
