version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # Use all available GPUs
              count: all
              capabilities: [gpu]
    networks:
      - searxng

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - "WEBUI_SECRET_KEY="
      - "RAG_WEB_SEARCH_ENGINE=searxng"
      - "SEARXNG_QUERY_URL=http://192.168.50.51:8888/search?q=<<query>>"
      - "ENABLE_RAG_WEB_SEARCH=true"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - searxng

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper
    ports:
      - "9000:9000"
    volumes:
      - whisper_cache:/root/.cache/whisper
      - ./audio:/audio
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=openai_whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  whisper_cache: {}

networks:
  searxng:
    name: searxng
