version: "3.1"

services:
  # linkedin_job_scraper:
  #   build: ./linkedin_job_scraper
  #   container_name: linkedin_job_scraper
  #   restart: unless-stopped
  #   ports:
  #     - "5001:5000"

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - TZ=${GENERIC_TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
      - N8N_SECURE_COOKIE=false
    depends_on:
      - postgres
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - n8n

  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - DATABASE_PROVIDER=postgresql
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - n8n

volumes:
  evolution_instances:
  redis_data:
  n8n_data: {}
  n8n_postgres_data: {}

networks:
  n8n:
    name: n8n
