version: "3.1"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secretpassword
      - TZ=America/New_York
    depends_on:
      - postgres
    user: 1000:1000
    volumes:
      - ./n8n_data:/home/node/.n8n

  postgres:
    image: postgres:15
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=n8n
    volumes:
      - ./n8n_postgres_data:/var/lib/postgresql/data

  fix-permissions:
    image: myapp
    user: root
    command: chmod -R 777 /home/node/.n8n
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - app
    restart: "no"
