version: "3.9"

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - 8888:8080
    volumes:
      - /searxng/:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888/
    restart: unless-stopped
    networks:
      - searxng
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - homepage.group=Search
      - homepage.name=SearXNG
      - homepage.icon=searxng.png
      - homepage.description=SearXNG is a self-hosted search engine.

  redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-redis
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  vane:
    image: itzcrazykns1337/vane:slim-latest
    container_name: vane
    ports:
      - "3030:3000"
    volumes:
      - vane-data:/home/vane/data
    environment:
      - SEARXNG_API_URL=http://192.168.50.18:8080/search?q=
      - OLLAMA_API_BASE_URL=http://192.168.50.18:11434/api
    depends_on:
      - searxng
    restart: unless-stopped
    networks:
      - searxng
    labels:
      - homepage.group=AI
      - homepage.name=Vane
      - homepage.icon=vane.png
      - homepage.description=Vane is a self-hosted AI assistant.

volumes:
  searxng-data:
  valkey-data2:
  vane-data:

networks:
  searxng:
    name: searxng
